// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd7QV0CoupwfWwyTagKP_MFZKHV6WSOrU',
    appId: '1:173138346508:web:72ebbb68dca033f739e429',
    messagingSenderId: '173138346508',
    projectId: 'gravity-b1648',
    authDomain: 'gravity-b1648.firebaseapp.com',
    storageBucket: 'gravity-b1648.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-dmRFgzTvzCncELgKGvwvq3j8HySZ62c',
    appId: '1:173138346508:android:55bf16af2acf49bf39e429',
    messagingSenderId: '173138346508',
    projectId: 'gravity-b1648',
    storageBucket: 'gravity-b1648.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB7vczwMCd59snmi_05f2S8zxSxS395B4',
    appId: '1:173138346508:ios:7b3258bb697632fc39e429',
    messagingSenderId: '173138346508',
    projectId: 'gravity-b1648',
    storageBucket: 'gravity-b1648.firebasestorage.app',
    iosBundleId: 'com.example.flutterplayground',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB7vczwMCd59snmi_05f2S8zxSxS395B4',
    appId: '1:173138346508:ios:7b3258bb697632fc39e429',
    messagingSenderId: '173138346508',
    projectId: 'gravity-b1648',
    storageBucket: 'gravity-b1648.firebasestorage.app',
    iosBundleId: 'com.example.flutterplayground',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd7QV0CoupwfWwyTagKP_MFZKHV6WSOrU',
    appId: '1:173138346508:web:ef9b6e4dd8dd215439e429',
    messagingSenderId: '173138346508',
    projectId: 'gravity-b1648',
    authDomain: 'gravity-b1648.firebaseapp.com',
    storageBucket: 'gravity-b1648.firebasestorage.app',
  );
}
